name: Linter

on:
  push:
    branches:
      - main
      - release-*
      - dev
  pull_request:
    branches:
      - main
      - release-*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
