name: Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'
      with:
        env_vars: |-
          OPENAI_API_KEY=OPENAI_API_KEY
          TELEGRAM_API_KEY=TELEGRAM_API_KEY