name: Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go version
      - run: go build -o telegram-bot
      - run: ./telegram-bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}